-- Migration: Add VPF (Voluntary Provident Fund) field to users table
-- Date: 2025-12-30
-- Description: Adds VPF field as an employee deduction under CTC & Salary tab

-- Add VPF column to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS vpf text;

-- Add comment for documentation
COMMENT ON COLUMN users.vpf IS 'VPF (Voluntary Provident Fund) - employee side deduction (editable)';

-- Drop existing functions first
DROP FUNCTION IF EXISTS get_employees_with_manager_details();
DROP FUNCTION IF EXISTS get_all_users_with_manager_details();

-- Update the get_employees_with_manager_details function to include VPF
CREATE OR REPLACE FUNCTION get_employees_with_manager_details()
RETURNS TABLE (
  id uuid,
  auth_provider text,
  provider_user_id text,
  email text,
  password_hash text,
  full_name text,
  employee_id text,
  role_id uuid,
  department_id uuid,
  "position" text,
  avatar_url text,
  phone text,
  address text,
  date_of_birth date,
  date_of_joining date,
  salary numeric,
  extra_permissions jsonb,
  status text,
  last_login timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  company_email text,
  manager_id uuid,
  tenure_mechlin interval,
  level_grade text,
  skill text[],
  current_office_location text,
  alternate_contact_no text,
  blood_group text,
  religion text,
  gender text,
  marital_status text,
  date_of_marriage_anniversary date,
  father_name text,
  father_dob date,
  mother_name text,
  mother_dob date,
  designation_offer_letter text,
  permanent_address text,
  aadhar_card_no text,
  pan_no text,
  personal_email text,
  bank_account_no text,
  ifsc_code text,
  qualification text,
  employment_terms text,
  "isSA" boolean,
  comp_off_balance numeric,
  -- Onboarding fields
  appointment_formalities text,
  orientation text,
  order_id_card text,
  email_account text,
  skype_account text,
  system_account text,
  added_to_mailing_list text,
  added_to_attendance_sheet text,
  confluence_info_provided text,
  id_card_provided text,
  remarks text,
  uan_number text,
  is_experienced text,
  -- Salary Annexure fields
  pf_applicable boolean,
  esi_applicable boolean,
  monthly_ctc text,
  monthly_basic_pay text,
  hra text,
  night_allowance text,
  special_allowance text,
  monthly_gross text,
  employer_pf text,
  employer_esi text,
  monthly_gratuity_provision text,
  monthly_bonus_provision text,
  group_medical_insurance text,
  pf_employee text,
  esi_employee text,
  tds text,
  professional_tax text,
  vpf text,
  total_deductions text,
  net_pay text,
  monthly_take_home_salary text,
  -- Loyalty Bonus fields
  loyalty_bonus_enrollment_date date,
  loyalty_bonus_specific_condition text,
  loyalty_bonus_tenure_period text,
  loyalty_bonus_amount text,
  loyalty_bonus_installment_1_amount text,
  loyalty_bonus_installment_2_amount text,
  loyalty_bonus_installment_3_amount text,
  loyalty_bonus_installment_4_amount text,
  loyalty_bonus_installment_5_amount text,
  loyalty_bonus_installment_6_amount text,
  loyalty_bonus_installment_1_date date,
  loyalty_bonus_installment_2_date date,
  loyalty_bonus_installment_3_date date,
  loyalty_bonus_installment_4_date date,
  loyalty_bonus_installment_5_date date,
  loyalty_bonus_installment_6_date date,
  loyalty_bonus_installment_1_disbursed boolean,
  loyalty_bonus_installment_2_disbursed boolean,
  loyalty_bonus_installment_3_disbursed boolean,
  loyalty_bonus_installment_4_disbursed boolean,
  loyalty_bonus_installment_5_disbursed boolean,
  loyalty_bonus_installment_6_disbursed boolean,
  -- Additional role fields
  additional_role_ids uuid[],
  role_name text,
  department_name text,
  manager_name text,
  manager_email text
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id,
    u.auth_provider,
    u.provider_user_id,
    u.email,
    u.password_hash,
    u.full_name,
    u.employee_id,
    u.role_id,
    u.department_id,
    u."position",
    u.avatar_url,
    u.phone,
    u.address,
    u.date_of_birth,
    u.date_of_joining,
    u.salary,
    u.extra_permissions,
    u.status,
    u.last_login,
    u.created_at,
    u.updated_at,
    u.company_email,
    u.manager_id,
    u.tenure_mechlin,
    u.level_grade,
    u.skill,
    u.current_office_location,
    u.alternate_contact_no,
    u.blood_group,
    u.religion,
    u.gender,
    u.marital_status,
    u.date_of_marriage_anniversary,
    u.father_name,
    u.father_dob,
    u.mother_name,
    u.mother_dob,
    u.designation_offer_letter,
    u.permanent_address,
    u.aadhar_card_no,
    u.pan_no,
    u.personal_email,
    u.bank_account_no,
    u.ifsc_code,
    u.qualification,
    u.employment_terms,
    u."isSA",
    u.comp_off_balance,
    -- Onboarding fields
    u.appointment_formalities,
    u.orientation,
    u.order_id_card,
    u.email_account,
    u.skype_account,
    u.system_account,
    u.added_to_mailing_list,
    u.added_to_attendance_sheet,
    u.confluence_info_provided,
    u.id_card_provided,
    u.remarks,
    u.uan_number,
    u.is_experienced,
    -- Salary Annexure fields
    u.pf_applicable,
    u.esi_applicable,
    u.monthly_ctc,
    u.monthly_basic_pay,
    u.hra,
    u.night_allowance,
    u.special_allowance,
    u.monthly_gross,
    u.employer_pf,
    u.employer_esi,
    u.monthly_gratuity_provision,
    u.monthly_bonus_provision,
    u.group_medical_insurance,
    u.pf_employee,
    u.esi_employee,
    u.tds,
    u.professional_tax,
    u.vpf,
    u.total_deductions,
    u.net_pay,
    u.monthly_take_home_salary,
    -- Loyalty Bonus fields
    u.loyalty_bonus_enrollment_date,
    u.loyalty_bonus_specific_condition,
    u.loyalty_bonus_tenure_period,
    u.loyalty_bonus_amount,
    u.loyalty_bonus_installment_1_amount,
    u.loyalty_bonus_installment_2_amount,
    u.loyalty_bonus_installment_3_amount,
    u.loyalty_bonus_installment_4_amount,
    u.loyalty_bonus_installment_5_amount,
    u.loyalty_bonus_installment_6_amount,
    u.loyalty_bonus_installment_1_date,
    u.loyalty_bonus_installment_2_date,
    u.loyalty_bonus_installment_3_date,
    u.loyalty_bonus_installment_4_date,
    u.loyalty_bonus_installment_5_date,
    u.loyalty_bonus_installment_6_date,
    u.loyalty_bonus_installment_1_disbursed,
    u.loyalty_bonus_installment_2_disbursed,
    u.loyalty_bonus_installment_3_disbursed,
    u.loyalty_bonus_installment_4_disbursed,
    u.loyalty_bonus_installment_5_disbursed,
    u.loyalty_bonus_installment_6_disbursed,
    -- Additional role fields
    u.additional_role_ids,
    r.name as role_name,
    d.name as department_name,
    m.full_name as manager_name,
    m.email as manager_email
  FROM users u
  LEFT JOIN roles r ON u.role_id = r.id
  LEFT JOIN departments d ON u.department_id = d.id
  LEFT JOIN users m ON u.manager_id = m.id
  WHERE u.status != 'deleted';
END;
$$ LANGUAGE plpgsql;

-- Update the get_all_users_with_manager_details function to include VPF
CREATE OR REPLACE FUNCTION get_all_users_with_manager_details()
RETURNS TABLE (
  id uuid,
  auth_provider text,
  provider_user_id text,
  email text,
  password_hash text,
  full_name text,
  employee_id text,
  role_id uuid,
  department_id uuid,
  "position" text,
  avatar_url text,
  phone text,
  address text,
  date_of_birth date,
  date_of_joining date,
  salary numeric,
  extra_permissions jsonb,
  status text,
  last_login timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  company_email text,
  manager_id uuid,
  tenure_mechlin interval,
  level_grade text,
  skill text[],
  current_office_location text,
  alternate_contact_no text,
  blood_group text,
  religion text,
  gender text,
  marital_status text,
  date_of_marriage_anniversary date,
  father_name text,
  father_dob date,
  mother_name text,
  mother_dob date,
  designation_offer_letter text,
  permanent_address text,
  aadhar_card_no text,
  pan_no text,
  personal_email text,
  bank_account_no text,
  ifsc_code text,
  qualification text,
  employment_terms text,
  "isSA" boolean,
  comp_off_balance numeric,
  -- Onboarding fields
  appointment_formalities text,
  orientation text,
  order_id_card text,
  email_account text,
  skype_account text,
  system_account text,
  added_to_mailing_list text,
  added_to_attendance_sheet text,
  confluence_info_provided text,
  id_card_provided text,
  remarks text,
  uan_number text,
  is_experienced text,
  -- Salary Annexure fields
  pf_applicable boolean,
  esi_applicable boolean,
  monthly_ctc text,
  monthly_basic_pay text,
  hra text,
  night_allowance text,
  special_allowance text,
  monthly_gross text,
  employer_pf text,
  employer_esi text,
  monthly_gratuity_provision text,
  monthly_bonus_provision text,
  group_medical_insurance text,
  pf_employee text,
  esi_employee text,
  tds text,
  professional_tax text,
  vpf text,
  total_deductions text,
  net_pay text,
  monthly_take_home_salary text,
  -- Loyalty Bonus fields
  loyalty_bonus_enrollment_date date,
  loyalty_bonus_specific_condition text,
  loyalty_bonus_tenure_period text,
  loyalty_bonus_amount text,
  loyalty_bonus_installment_1_amount text,
  loyalty_bonus_installment_2_amount text,
  loyalty_bonus_installment_3_amount text,
  loyalty_bonus_installment_4_amount text,
  loyalty_bonus_installment_5_amount text,
  loyalty_bonus_installment_6_amount text,
  loyalty_bonus_installment_1_date date,
  loyalty_bonus_installment_2_date date,
  loyalty_bonus_installment_3_date date,
  loyalty_bonus_installment_4_date date,
  loyalty_bonus_installment_5_date date,
  loyalty_bonus_installment_6_date date,
  loyalty_bonus_installment_1_disbursed boolean,
  loyalty_bonus_installment_2_disbursed boolean,
  loyalty_bonus_installment_3_disbursed boolean,
  loyalty_bonus_installment_4_disbursed boolean,
  loyalty_bonus_installment_5_disbursed boolean,
  loyalty_bonus_installment_6_disbursed boolean,
  -- Additional role fields
  additional_role_ids uuid[],
  role_name text,
  department_name text,
  manager_name text,
  manager_email text
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id,
    u.auth_provider,
    u.provider_user_id,
    u.email,
    u.password_hash,
    u.full_name,
    u.employee_id,
    u.role_id,
    u.department_id,
    u."position",
    u.avatar_url,
    u.phone,
    u.address,
    u.date_of_birth,
    u.date_of_joining,
    u.salary,
    u.extra_permissions,
    u.status,
    u.last_login,
    u.created_at,
    u.updated_at,
    u.company_email,
    u.manager_id,
    u.tenure_mechlin,
    u.level_grade,
    u.skill,
    u.current_office_location,
    u.alternate_contact_no,
    u.blood_group,
    u.religion,
    u.gender,
    u.marital_status,
    u.date_of_marriage_anniversary,
    u.father_name,
    u.father_dob,
    u.mother_name,
    u.mother_dob,
    u.designation_offer_letter,
    u.permanent_address,
    u.aadhar_card_no,
    u.pan_no,
    u.personal_email,
    u.bank_account_no,
    u.ifsc_code,
    u.qualification,
    u.employment_terms,
    u."isSA",
    u.comp_off_balance,
    -- Onboarding fields
    u.appointment_formalities,
    u.orientation,
    u.order_id_card,
    u.email_account,
    u.skype_account,
    u.system_account,
    u.added_to_mailing_list,
    u.added_to_attendance_sheet,
    u.confluence_info_provided,
    u.id_card_provided,
    u.remarks,
    u.uan_number,
    u.is_experienced,
    -- Salary Annexure fields
    u.pf_applicable,
    u.esi_applicable,
    u.monthly_ctc,
    u.monthly_basic_pay,
    u.hra,
    u.night_allowance,
    u.special_allowance,
    u.monthly_gross,
    u.employer_pf,
    u.employer_esi,
    u.monthly_gratuity_provision,
    u.monthly_bonus_provision,
    u.group_medical_insurance,
    u.pf_employee,
    u.esi_employee,
    u.tds,
    u.professional_tax,
    u.vpf,
    u.total_deductions,
    u.net_pay,
    u.monthly_take_home_salary,
    -- Loyalty Bonus fields
    u.loyalty_bonus_enrollment_date,
    u.loyalty_bonus_specific_condition,
    u.loyalty_bonus_tenure_period,
    u.loyalty_bonus_amount,
    u.loyalty_bonus_installment_1_amount,
    u.loyalty_bonus_installment_2_amount,
    u.loyalty_bonus_installment_3_amount,
    u.loyalty_bonus_installment_4_amount,
    u.loyalty_bonus_installment_5_amount,
    u.loyalty_bonus_installment_6_amount,
    u.loyalty_bonus_installment_1_date,
    u.loyalty_bonus_installment_2_date,
    u.loyalty_bonus_installment_3_date,
    u.loyalty_bonus_installment_4_date,
    u.loyalty_bonus_installment_5_date,
    u.loyalty_bonus_installment_6_date,
    u.loyalty_bonus_installment_1_disbursed,
    u.loyalty_bonus_installment_2_disbursed,
    u.loyalty_bonus_installment_3_disbursed,
    u.loyalty_bonus_installment_4_disbursed,
    u.loyalty_bonus_installment_5_disbursed,
    u.loyalty_bonus_installment_6_disbursed,
    -- Additional role fields
    u.additional_role_ids,
    r.name as role_name,
    d.name as department_name,
    m.full_name as manager_name,
    m.email as manager_email
  FROM users u
  LEFT JOIN roles r ON u.role_id = r.id
  LEFT JOIN departments d ON u.department_id = d.id
  LEFT JOIN users m ON u.manager_id = m.id;
END;
$$ LANGUAGE plpgsql;
